# Generated by Django 5.0.6 on 2025-11-28 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='dificultad_percibida',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil')], help_text='Dificultad percibida del ejercicio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='dolor_ejecucion',
            field=models.IntegerField(blank=True, help_text='Nivel de dolor durante el ejercicio (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
