# Generated by Django 5.0.6 on 2025-11-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='frecuencia_semanal',
            field=models.IntegerField(blank=True, help_text='Días de ejercicio por semana', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Masa Corporal', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='intensidad',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta')], help_text='Intensidad del ejercicio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='porcentaje_grasa_corporal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de grasa corporal', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='progreso_positivo',
            field=models.BooleanField(default=False, help_text='¿Hubo progreso positivo?'),
        ),
        migrations.AddField(
            model_name='cita',
            name='repeticiones',
            field=models.IntegerField(blank=True, help_text='Número de repeticiones', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiempo',
            field=models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_ejercicio',
            field=models.CharField(blank=True, help_text='Tipo de ejercicio realizado', max_length=255, null=True),
        ),
    ]
